nav:
  Home: /
  Public speaking: /speaking/
  Blog: /archives/
  About: /about/

projects_url: http://fhinkel.github.io

customize:
    gravatar:
        email: fhinkel@vt.edu
    logo:
        enabled: true
        width: 50
        height: 50
        url: /images/logo.png
        gravatar: false
    favicon: 
      # eg. generate with http://realfavicongenerator.net/
      desktop:
        url: /images/favicon.ico
        gravatar: false
      android:
        url: /images/favicon-192x192.png
        gravator: false
      apple:
        url: /images/apple-touch-icon.png
        gravator: false
    social_links:
        github: http://github.com/fhinkel
        twitter: http://twitter.com/fhinkel
        linkedin: https://www.linkedin.com/in/fhinkel/
        medium: https://medium.com/@fhinkel
    show_all_posts: false
    post_count: 5
    highlight: rainbow

# RSS
# if plugin, use the hexo-generator-feed plugin.
rss: plugin


# Plugins
plugins:
    disqus_shortname: # Disqus Comments Shortname
    google_analytics: UA-111379301-2 # enter the tracking ID for your Google Analytics

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        twitter_id: '@fhinkel'
        image: images/hinkelmann.jpeg
